#ifndef __ihmc_sake_ros2__msg__EZGripperCommand__idl__
#define __ihmc_sake_ros2__msg__EZGripperCommand__idl__

module ihmc_sake_ros2
{
  module msg
  {
    module dds
    {
      const octet LEFT =
      0;

      const octet RIGHT =
      1;


      @TypeCode(type="ihmc_sake_ros2::msg::dds_::EZGripperCommand_")
      struct EZGripperCommand
      {
        /**
         * Specifies the side of the robot of the gripper being referred to
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * Request the gripper to perform a calibration sequence
         */
        boolean calibrate;
        /**
         * Request to reset the gripper error state after overheating
         */
        boolean reset_errors;
        /**
         * Set to true to enable automatic cooldown
         */
        boolean enable_auto_cooldown;
        /**
         * Set to true to override the cooldown
         */
        boolean override_cooldown;
        /**
         * The goal position
         * 0.0 = fully closed, 1.0 = fully open
         */
        float goal_position;
        /**
         * Maximum effort to put into achieving the goal position
         * 0.0 = no effort (fingers will not move), 1.0 = maximum effort (can quickly overheat actuator)
         * 0.3 is a reasonable normal value, and it is recommended not to exceed 0.8.
         */
        float max_effort;
        /**
         * Keeping the torque off when not needed can help keep the gripper's temperature down
         */
        boolean torque_on;
      };
    };
  };
};

#endif
